# Pandas (1)

In [1]:
import pandas as pd
import numpy as np

## Лабораторная работа №2.1

### Базовые операции с `DataFrame`

1.1 В файлах `recipes_sample.csv` и `reviews_sample.csv` находится информация об рецептах блюд и отзывах на эти рецепты соответственно. Загрузите данные из файлов в виде `pd.DataFrame` с названиями `recipes` и `reviews`. Обратите внимание на корректное считывание столбца с индексами в таблице `reviews` (безымянный столбец).

In [2]:
recipes = pd.read_csv('recipes_sample.csv', sep = ',')
recipes

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29995,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
29997,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
29998,zydeco soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN
29999,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

In [3]:
reviews = pd.read_csv('reviews_sample.csv', sep = ',', index_col = 0)
reviews

,user_id,recipe_id,date,rating,review
370476,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
624300,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...
187037,400708,252013,2008-01-10,4,"Very nice breakfast HH, easy to make and yummy..."
706134,2001852463,404716,2017-12-11,5,These are a favorite for the holidays and so e...
312179,95810,129396,2008-03-14,5,Excellent soup! The tomato flavor is just gre...
...,...,...,...,...,...
1013457,1270706,335534,2009-05-17,4,This recipe was great! I made it last night. I...
158736,2282344,8701,2012-06-03,0,This recipe is outstanding. I followed the rec...
1059834,689540,222001,2008-04-08,5,"Well, we were not a crowd but it was a fabulou..."
453285,2000242659,354979,2015-06-02,5,I have been a steak eater and dedicated BBQ gr...
691207,463435,415599,2010-09-30,5,Wonderful and simple to prepare seasoning blen...

1.2 Для каждой из таблиц выведите основные параметры:
* количество точек данных (строк);
* количество столбцов;
* тип данных каждого столбца.

In [5]:
recipes_len = len(recipes)
reviews_len = len(reviews)

In [14]:
recipes_len, reviews_len

(30000, 126696)

In [15]:
recipes_width = recipes.shape[1]
reviews_width = reviews.shape[1]

In [16]:
recipes_width, reviews_width

(8, 5)

In [17]:
recipes.dtypes

name               object
id                  int64
minutes             int64
contributor_id      int64
submitted          object
n_steps           float64
description        object
n_ingredients     float64
dtype: object

In [18]:
reviews.dtypes

user_id       int64
recipe_id     int64
date         object
rating        int64
review       object
dtype: object

1.3 Исследуйте, в каких столбцах таблиц содержатся пропуски. Посчитайте долю строк, содержащих пропуски, в отношении к общему количеству строк.

In [19]:
recipes.isnull().sum(axis=0)

name                  0
id                    0
minutes               0
contributor_id        0
submitted             0
n_steps           11190
description         623
n_ingredients      8880
dtype: int64

In [20]:
reviews.isnull().sum(axis=0)

user_id       0
recipe_id     0
date          0
rating        0
review       17
dtype: int64

In [21]:
(recipes.isnull().sum(axis=1)>0).sum()/len(recipes)

0.5684666666666667

In [22]:
(reviews.isnull().sum(axis=1)>0).sum()/len(reviews)

0.00013417945317926376

1.4 Рассчитайте и выведите на экран среднее значение для каждого из числовых столбцов (где это имеет смысл).

In [23]:
means_recipes = recipes.mean(numeric_only = True)
means_recipes[[col for col in means_recipes.index if "id" not in col]]

minutes          123.358133
n_steps            9.805582
n_ingredients      9.008286
dtype: float64

In [24]:
means_reviews = reviews.mean(numeric_only = True)
means_reviews[[col for col in means_reviews.index if "id" not in col]]

rating    4.410802
dtype: float64

In [25]:
reviews.mean(numeric_only = True)

user_id      1.408013e+08
recipe_id    1.600944e+05
rating       4.410802e+00
dtype: float64

1.5 Создайте и выведите на экран 10 случайных названий рецептов.

In [26]:
rand_recipes = np.random.randint(0, recipes_len + 1, size = 10)
recipes.iloc[rand_recipes]

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
15344,kid friendly chicken and biscuits,324414,50,311003,2008-09-10,NaN,"this casserole is super-quick to put together,...",7.0
16671,macaroni and cheese pie,299146,30,731027,2008-04-17,NaN,"who doesn't like cheese and pie? well, this re...",11.0
9139,dark creamy chocolate cake,412284,35,216999,2010-02-08,NaN,taken from the magazine section of the 2/7/10 ...,6.0
9175,davey s broiled yellowfin tuna and relish,117342,40,134875,2005-04-15,8.0,this is a concotion made up by my husband. it...,23.0
20004,pasta with raw tomato and balsamic sauce,170216,30,67728,2006-05-29,7.0,i think i found this recipe at a local farmers...,10.0
8396,creamy vanilla iced coffee,69162,15,52362,2003-08-20,NaN,i based this recipe from the starbucks iced co...,NaN
8953,curried beef dumplings,492719,110,714468,2013-01-01,22.0,from carla hall's cooking with love. be sure ...,12.0
6792,chocolate wafer cookies like nabisco chocolat...,329292,37,68526,2008-10-07,28.0,remember the ice box cake back in the 60's and...,10.0
11135,florida snapper with couscous,256544,35,426229,2007-10-01,7.0,i adapted this recipe from food reference.com....,13.0
26570,sweet savory roasted spiced walnuts,442249,45,225426,2010-11-17,NaN,these addictively delicious walnuts make for c...,9.0

1.6 Выведите на экран строку с __номером__ `54200`. Выведите на экран строку с __индексом__ `54200`.

In [27]:
reviews.iloc[54200] #индекс

user_id                                                 813584
recipe_id                                                  916
date                                                2008-08-16
rating                                                       5
review       I've made this 3-4 times already and forgot to...
Name: 667742, dtype: object

In [28]:
reviews.loc[54200] #номер

user_id                                                 853909
recipe_id                                                51058
date                                                2008-12-30
rating                                                       0
review       Excellent recipe!  My picky eaters love this. ...
Name: 54200, dtype: object

1.7 Измените индекс в таблице `reviews`, пронумеровав строки, начиная с нуля.

In [29]:
reviews.index = np.arange(0, reviews_len)
reviews

,user_id,recipe_id,date,rating,review
0,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
1,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...
2,400708,252013,2008-01-10,4,"Very nice breakfast HH, easy to make and yummy..."
3,2001852463,404716,2017-12-11,5,These are a favorite for the holidays and so e...
4,95810,129396,2008-03-14,5,Excellent soup! The tomato flavor is just gre...
...,...,...,...,...,...
126691,1270706,335534,2009-05-17,4,This recipe was great! I made it last night. I...
126692,2282344,8701,2012-06-03,0,This recipe is outstanding. I followed the rec...
126693,689540,222001,2008-04-08,5,"Well, we were not a crowd but it was a fabulou..."
126694,2000242659,354979,2015-06-02,5,I have been a steak eater and dedicated BBQ gr...
126695,463435,415599,2010-09-30,5,Wonderful and simple to prepare seasoning blen...

1.8 Выведите информацию о рецептах, время выполнения которых не больше 20 минут и кол-во ингредиентов в которых не больше 5.

In [30]:
recipes[(recipes['minutes'] <= 20) &
        (recipes['n_ingredients'] <= 5)]

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
28,quick biscuit bread,302399,20,213909,2008-05-06,11.0,this is a wonderful quick bread to make as an ...,5.0
60,peas fit for a king or queen,303944,20,213909,2008-05-16,NaN,this recipe is so simple and the flavors are s...,5.0
90,hawaiian sunrise mimosa,100837,5,58104,2004-09-29,4.0,pineapple mimosa was changed to hawaiian sunri...,3.0
91,tasty dish s banana pudding in 2 minutes,286484,2,47892,2008-02-13,NaN,"""mmmm, i love bananas!"" a --tasty dish-- origi...",4.0
94,1 minute meatballs,11361,13,4470,2001-09-03,NaN,this is a real short cut for cooks in a hurry....,2.0
...,...,...,...,...,...,...,...,...
29873,zip and steam red potatoes with butter and garlic,304922,13,724218,2008-05-27,9.0,"i haven't tried this yet, but i am going to so...",5.0
29874,ziplock vanilla ice cream,74250,10,24386,2003-10-29,8.0,a fun thing for kids to do. may want to use mi...,3.0
29905,zucchini and corn with cheese,256177,15,305531,2007-09-29,4.0,from betty crocker fresh spring recipes. i lik...,5.0
29980,zucchini with jalapeno monterey jack,320622,10,305531,2008-08-20,3.0,simple and yummy!,3.0
29983,zucchini with serrano ham,162411,15,152500,2006-03-31,6.0,"this dish is from tim malzer, a german chef wh...",5.0

### Работа с датами в `pandas`

2.1 Преобразуйте столбец `submitted` из таблицы `recipes` в формат времени. Модифицируйте решение задачи 1.1 так, чтобы считать столбец сразу в нужном формате.

In [31]:
recipes['submitted'] = pd.to_datetime(recipes['submitted'])

In [32]:
recipes.dtypes

name                      object
id                         int64
minutes                    int64
contributor_id             int64
submitted         datetime64[ns]
n_steps                  float64
description               object
n_ingredients            float64
dtype: object

In [33]:
recipes = pd.read_csv('recipes_sample.csv', sep = ',', parse_dates=['submitted'])
recipes

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29995,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
29997,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
29998,zydeco soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN
29999,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

In [34]:
recipes.dtypes

name                      object
id                         int64
minutes                    int64
contributor_id             int64
submitted         datetime64[ns]
n_steps                  float64
description               object
n_ingredients            float64
dtype: object

2.2 Выведите информацию о рецептах, добавленных в датасет не позже 2010 года.

In [35]:
recipes[recipes['submitted'].dt.year <= 2010]

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29993,zuni caf zucchini pickles,316950,2895,62264,2008-07-31,NaN,refrigerator pickles for some of the zucchini ...,8.0
29995,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
29997,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
29999,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

In [36]:
recipes[(recipes['submitted'] < '2011-01-01')]

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29993,zuni caf zucchini pickles,316950,2895,62264,2008-07-31,NaN,refrigerator pickles for some of the zucchini ...,8.0
29995,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
29997,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
29999,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

### Работа со строковыми данными в `pandas`

3.1  Добавьте в таблицу `recipes` столбец `description_length`, в котором хранится длина описания рецепта из столбца `description`.

In [37]:
description_length = recipes.description.str.len()
description_length

0        330.0
1        255.0
2         39.0
3        154.0
4        587.0
         ...
29995    484.0
29996    286.0
29997    311.0
29998    648.0
29999    125.0
Name: description, Length: 30000, dtype: float64

In [38]:
recipes['description_length'] = description_length
recipes

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0
...,...,...,...,...,...,...,...,...,...
29995,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0,484.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0,286.0
29997,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN,311.0
29998,zydeco soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,648.0
29999,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0,125.0

3.2 Измените название каждого рецепта в таблице `recipes` таким образом, чтобы каждое слово в названии начиналось с прописной буквы.

In [39]:
recipes.name = recipes.name.str.title()
recipes

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length
0,George S At The Cove Black Bean Soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0
1,Healthy For Them Yogurt Popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0
2,I Can T Believe It S Spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0
3,Italian Gut Busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0
4,Love Is In The Air Beef Fondue Sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0
...,...,...,...,...,...,...,...,...,...
29995,Zurie S Holey Rustic Olive And Cheddar Bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0,484.0
29996,Zwetschgenkuchen Bavarian Plum Cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0,286.0
29997,Zwiebelkuchen Southwest German Onion Cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN,311.0
29998,Zydeco Soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,648.0
29999,Cookies By Design Cookies On A Stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0,125.0

3.3 Добавьте в таблицу `recipes` столбец `name_word_count`, в котором хранится количество слов из названии рецепта (считайте, что слова в названии разделяются только пробелами). Обратите внимание, что между словами может располагаться несколько пробелов подряд.

In [40]:
recipes['name_word_count'] = recipes.name.str.split().str.len()

In [41]:
recipes

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length,name_word_count
0,George S At The Cove Black Bean Soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0,8
1,Healthy For Them Yogurt Popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0,5
2,I Can T Believe It S Spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0,7
3,Italian Gut Busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0,3
4,Love Is In The Air Beef Fondue Sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0,8
...,...,...,...,...,...,...,...,...,...,...
29995,Zurie S Holey Rustic Olive And Cheddar Bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0,484.0,8
29996,Zwetschgenkuchen Bavarian Plum Cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0,286.0,4
29997,Zwiebelkuchen Southwest German Onion Cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN,311.0,5
29998,Zydeco Soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,648.0,2
29999,Cookies By Design Cookies On A Stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0,125.0,7